# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ce14d86c-c176-43c3-80b2-e1fdffed51e6";
      fsType = "btrfs";
      options = [ "subvol=/" "compress=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ce14d86c-c176-43c3-80b2-e1fdffed51e6";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ce14d86c-c176-43c3-80b2-e1fdffed51e6";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/516A-BC91";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
